# Generated by Django 4.2.28 on 2026-03-01 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('students', models.ManyToManyField(blank=True, related_name='groups', to='students.student')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['school', 'name'], name='students_st_school__ad0a5c_idx')],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'last_name', 'first_name'], name='students_st_school__34fb6f_idx'),
        ),
    ]
